### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by lindaro** [pudo/aleph#61]
Just getting started with this project, can you provide some information on how to import documents to particular collections?

uploading via webUI seems to not work.

using file as archive system if that helps.

**Comment by pudo** [comment]
[Here's](https://github.com/pudo/aleph/wiki/Usage) a bunch of different options for loading data into the system. But it sounds like you actually have a configuration issue, not just a usage thing. Can you give any details on what happens when you try and upload something via the web UI? Are there any console errors in the browser? Anything in the server logs?

**Comment by lindaro** [comment]
did a crawldir earlier on a bunch of text files, the collection was created but it does not reflect this in the webUI; could be a config problem.

As for the web upload, there's no errors on the browser console, and docker log on web shows
```

7/30/2016 8:14:14 PMDEBUG:aleph.search.documents:Query ES time: 18.78595ms
7/30/2016 8:14:14 PMDEBUG:aleph.search.documents:Post-facet accumulated: 19.08612ms
7/30/2016 8:14:14 PMDEBUG:aleph.search.documents:Post-subquery accumulated: 19.26899ms
```

which I imagine is working fine. Let me know if you need more information. containers were built on latest master

**Comment by pudo** [comment]
So the probable reason for crawldir not showing up is that the collections are created so that only admins can see them initially. You need to make one admin account, usually through flipping a bit in the database: ``UPDATE role SET is_admin = true WHERE email = '...';``. As for the web upload: do both containers have access to the same volume mount used for storing the files?

**Comment by lindaro** [comment]
Sorry took so long to get back to you. Had a chance to look at this again today.
you are indeed correct, both the `worker` and `web` container needs to access the folder defined in path for this to work. In addition the admin account query you provided have also had great effect; adding them to the wiki would be appreciated for future users.

Now, I've uploaded some PDFs to great effect.
- the show up in the UI
- entity extract seems to be working as they ask me to sort through newly detected organizations and users.

However when I tried to upload a simple .txt file containing a raw email it doesn't seem to do anything.
Is there a way to make `workerer` more verbose btw? I hate to bug you for every little thing.

**Comment by pudo** [comment]
No worries, glad to hear it works for you! Regarding the worker verbosity -- it's already pretty high, are you seeing messages similar to the ones that @jbothma attached to #66? If not, please give me some detail on how you're running this the app :) 

Regarding ``.txt`` files: I used to treat them as documents, but in most of the datasets which we import that actually just turned out to be lots of empty dummy files. If you want to activate this behaviour, add ``txt`` here: https://github.com/pudo/aleph/blob/master/aleph/ingest/document.py#L21 

If the the files are proper RFC822 emails, you can also add them to the email parser to have them properly parsed (attachments unpacked etc. etc.): https://github.com/pudo/aleph/blob/master/aleph/ingest/email.py#L23

**Comment by pudo** [comment]
I'm going to close this issue because it's not about one specific problem -- please feel free to open other, more specific issues or to write to the [mailing list](https://groups.google.com/forum/#!forum/aleph-search) with more abstract concerns.
