### ISSUE TITLE
Search results should be highlighted in the page

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#72]

**Comment by pudo** [comment]
This is currently a constraint in the way we embed ``pdf.js``, it doesn't actually render out the text at all (instead, it simply generates a canvas to show the rendered PDF). This probably means setting up PDF.js manually instead of using an existing angular binding. Here's [some discussion about the PDF.js aspect of this](https://github.com/mozilla/pdf.js/pull/5496).

**Comment by jbothma** [comment]
too bad. how about closing for now with a tag like "parked"?
